### PR TITLE
refactored to stop using deprecated 'DescribeJobFlows' API via Boto

### PR DESCRIPTION
**Pull request by msharp**
AWS will kill the 'DescribeJobFlows' API on December 14.

This change uses the new "cluster" terminology in stead of "job flow" and accesses, via Boto, the new APIs for information about the running jobs.

### CODE REVIEW

**Comment by JonathanBatten** [comment]
Deprecated API:
http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html

New API:
http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeCluster.html
http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_ListSteps.html

**Comment by JonathanBatten** [comment]
Re: changes in the requirements file.

https://github.com/msharp/apiarist/pull/2/files#diff-b4ef698db8ca845e5845c4618278f29a

I can't see the belowrequirements from the updated boto package directly, are these nested requirements from its requirements or from somewhere else?

docutils==0.12
futures==2.2.0
jmespath==0.9.0
python-dateutil==2.4.2
six==1.10.0

**Comment by msharp** [comment]
Not sure about those. May have crept in inadvertently.

The requirements file is not used to build the package which is distributed, those dependencies are declared in `setup.py` (the only dependency is Boto)

It's really just for development (e.g. pyflakes and pep8)

**Comment by JonathanBatten** [comment]
Ok, all good.

PASS REVIEW

**Pull request merged**
